# Generated by Django 2.2 on 2020-07-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0002_message_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_post',
            name='user_who_liked',
            field=models.ManyToManyField(related_name='liked_post', to='db_app.User'),
        ),
    ]
